### ISSUE TITLE
 nncv :command not found

### ISSUE THREAD

**Issue by yinyiyu** [a312863063/generators-with-stylegan2#10]
您好，我在允许main.py后出现了nvcc命令找不到的错误，请问是需要安装什么包吗  我是在ubuntu下面进行实验的

**Comment by HqWei** [comment]
同问

**Comment by yinyiyu** [comment]
我发现了 好想是需要手动安装cuda tools和cudnn，然后将ops里面的msvc版本替换为自己的版本才行。这里可能是作者自己写了个什么加速优化的方法吧，pytorch里面只是安装了运行时环境 并没有安装sdk  所以这里需要有sdk的支持，需要手动安装

**Comment by HqWei** [comment]
@yinyiyu 
装下面这些库文件吗：

compiler_bindir_search_path = [
    'C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64',
    'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64',
    'C:/Program Files (x86)/Microsoft Visual Studio 14.0/vc/bin',
]

**Comment by yinyiyu** [comment]
不是  只是装cuda  和cudnn 两个然后安装vs的时候  记得把桌面开发c++选上，然后会在上面的目录下面有自己的版本，看你是用的vs19 还是vs17  在C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/下查看自己的版本号，然后修改对应的位置就行了

**Comment by HqWei** [comment]
你也在win上进行了啊，前面你说你在ubuntu上

**Comment by HqWei** [comment]
> 你也在win上进行了啊，前面你说你在ubuntu上

@yinyiyu

**Comment by yinyiyu** [comment]
是的  我后面到windows上面进行实验的 因为实验室的ubuntu是大家公用的，担心安装cuda等一系列的东西会出现问题，如果是个人的机器就不存在

**Comment by HqWei** [comment]
在windows上能跑通人脸编辑的功能是吧？

**Comment by HqWei** [comment]
> 在windows上能跑通人脸编辑的功能是吧？
@yinyiyu

**Comment by yinyiyu** [comment]
没有跑过  生成模型都能跑

**Comment by HqWei** [comment]
生成模型我在linux也可以跑通，但人脸编辑不行，编译通不过

**Comment by yinyiyu** [comment]
你不是在linux没有找到nvcc吗

**Comment by zhangbaijin** [comment]
老哥你好，我也遇到了同样的问题，如果是在linux上运行的话，安装一下cuda和cudnn就行了吗

**Comment by yinyiyu** [comment]
是的  必须是cuda的编译环境 就是你需要去cuda官网找安装包下载那种

**Comment by Sparks-Lu** [comment]
Linux下的话，要把/usr/local/cuda/bin添加到PATH环境变量里，就可以找到nvcc了
